# entities.yaml
# Wygenerowane na podstawie docs/entities.md

entities:
  - id: basic-mine
    name: Podstawowa kopalnia
    tier: 1
    type: wydobycie
    cost: [ {itemId: iron-plate, qty: 5} ]
    function: Wydobywa rudę (0,2/s)
    operation_cost: 10 kW
    tech_requirement: initial

  - id: automatic-mine
    name: Kopalnia automatyczna
    tier: 1
    type: wydobycie
    cost: [ {itemId: iron-plate, qty: 10}, {itemId: gear-wheel, qty: 5} ]
    function: Wydobywa rudę (1/s)
    operation_cost: 50 kW
    tech_requirement: efficient-mining

  - id: ore-separator
    name: Separator rud
    tier: 1
    type: wydobycie
    cost: [ {itemId: iron-plate, qty: 15}, {itemId: gear-wheel, qty: 10}, {itemId: electronic-circuit, qty: 5} ]
    function: Przetwarza rudę w koncentrat (+20%)
    operation_cost: 30 kW
    tech_requirement: ore-enrichment
  - id: stone-furnace
    name: Piec kamienny
    tier: 1
    type: przetwarzanie
    cost: [ {itemId: stone, qty: 5} ]
    function: 1 ruda → 1 płytka
    operation_cost: Paliwo stałe (węgiel)
    tech_requirement: initial

  - id: conveyor-tier-1
    name: Przenośnik Tier 1
    tier: 1
    type: transport
    cost: [ {itemId: iron-plate, qty: 1}, {itemId: gear-wheel, qty: 1} ]
    function: Transport przedmiotów (5/s)
    operation_cost: Brak
    tech_requirement: initial

  - id: basic-storage
    name: Magazyn podstawowy
    tier: 1
    type: magazyn
    cost: [ {itemId: iron-plate, qty: 5} ]
    function: Przechowuje 100 jedn. surowców
    operation_cost: Brak
    tech_requirement: initial
  - id: blast-furnace
    name: Hutnia wielkopiecowa
    tier: 2
    type: przetwarzanie
    cost: [ {itemId: iron-plate, qty: 30}, {itemId: stone, qty: 10}, {itemId: electronic-circuit, qty: 5} ]
    function: Przetwarza rudę na sztabki szybciej (+2/s)
    operation_cost: 90 kW
    tech_requirement: metallurgical-patterns

  - id: conveyor-tier-2
    name: Przenośnik Tier 2
    tier: 2
    type: transport
    cost: [ {itemId: iron-plate, qty: 1}, {itemId: electronic-circuit, qty: 1} ]
    function: Transport przedmiotów (10/s)
    operation_cost: Brak
    tech_requirement: metallurgical-patterns

  - id: advanced-storage
    name: Magazyn zaawansowany
    tier: 2
    type: magazyn
    cost: [ {itemId: iron-plate, qty: 10}, {itemId: electronic-circuit, qty: 2} ]
    function: Przechowuje 500 jedn. surowców
    operation_cost: Brak
    tech_requirement: metallurgical-patterns
  - id: thermosolar-generator
    name: Generator termosolar
    tier: 2
    type: energia
    cost: [ {itemId: iron-plate, qty: 10}, {itemId: copper-plate, qty: 5}, {itemId: electronic-circuit, qty: 2} ]
    function: Pasywna produkcja energii (+5 jedn./s)
    operation_cost: Brak
    tech_requirement: energy-modules

  - id: energy-accumulator
    name: Akumulator energetyczny
    tier: 2
    type: energia
    cost: [ {itemId: iron-plate, qty: 5}, {itemId: copper-plate, qty: 2} ]
    function: Magazynuje energię (500 kW)
    operation_cost: Brak
    tech_requirement: energy-modules

  - id: assembler-tier-1
    name: Assembler Tier 1
    tier: 3
    type: produkcja
    cost: [ {itemId: iron-plate, qty: 15}, {itemId: gear-wheel, qty: 5}, {itemId: electronic-circuit, qty: 3} ]
    function: Automatycznie wytwarza komponenty (1/s)
    operation_cost: 75 kW
    tech_requirement: speed-modules
  - id: biomass-reactor
    name: Reaktor biomasowy
    tier: 3
    type: energia
    cost: [ {itemId: iron-plate, qty: 20}, {itemId: copper-plate, qty: 10}, {itemId: electronic-circuit, qty: 5} ]
    function: Produkcja energii z biomasy (+8 jedn./s)
    operation_cost: Biomasa
    tech_requirement: productivity-modules

  - id: basic-laboratory
    name: Laboratorium podstawowe
    tier: 3
    type: badania
    cost: [ {itemId: iron-plate, qty: 10}, {itemId: electronic-circuit, qty: 10}, {itemId: copper-plate, qty: 5} ]
    function: Konsumpcja pakietów badań (1/s)
    operation_cost: 60 kW
    tech_requirement: initial

  - id: super-laboratory
    name: Laboratorium Super
    tier: 3
    type: badania
    cost: [ {itemId: iron-plate, qty: 20}, {itemId: electronic-circuit, qty: 15}, {itemId: steel-plate, qty: 10} ]
    function: Przyspieszone badania (+15%)
    operation_cost: 120 kW
    tech_requirement: accelerated-research
  - id: chemical-plant
    name: Zakład chemiczny
    tier: 4
    type: chemia
    cost: [ {itemId: iron-plate, qty: 30}, {itemId: gear-wheel, qty: 10}, {itemId: pipe, qty: 5}, {itemId: electronic-circuit, qty: 5} ]
    function: Produkcja chemikaliów (+3 jedn./s)
    operation_cost: 210 kW
    tech_requirement: chemical-catalysts

  - id: metal-roller
    name: Walcer metali
    tier: 4
    type: przetwarzanie
    cost: [ {itemId: iron-plate, qty: 50}, {itemId: steel-plate, qty: 20}, {itemId: gear-wheel, qty: 10}, {itemId: advanced-circuit, qty: 5} ]
    function: Automatyczna obróbka metalu (+5 sztabek/s)
    operation_cost: 180 kW
    tech_requirement: enriched-alloy

  - id: storage-tier-3
    name: Magazyn Tier 3
    tier: 4
    type: magazyn
    cost: [ {itemId: steel-plate, qty: 20}, {itemId: advanced-circuit, qty: 5} ]
    function: Przechowuje 2000 jedn. surowców
    operation_cost: Brak
    tech_requirement: enriched-alloy
  - id: basic-nuclear-reactor
    name: Reaktor jądrowy (podstawowy)
    tier: 5
    type: energia
    cost: [ {itemId: steel-plate, qty: 100}, {itemId: advanced-circuit, qty: 50}, {itemId: pipe, qty: 20}, {itemId: heat-exchanger, qty: 10} ]
    function: Produkcja energii (+50 jedn./s)
    operation_cost: Paliwo jądrowe
    tech_requirement: basic-nuclear-reactor

  - id: autonomous-cooling-modules
    name: Autonomiczne moduły chłodzenia
    tier: 5
    type: energia
    cost: [ {itemId: steel-plate, qty: 30}, {itemId: advanced-circuit, qty: 20}, {itemId: pipe, qty: 15} ]
    function: +20% czasu pracy reaktora
    operation_cost: 50 kW
    tech_requirement: autonomous-cooling-modules

  - id: advanced-nuclear-reactor
    name: Reaktor jądrowy (zaawansowany)
    tier: 5
    type: energia
    cost: [ {itemId: steel-plate, qty: 200}, {itemId: advanced-circuit, qty: 100}, {itemId: heat-exchanger, qty: 50} ]
    function: Produkcja energii (+100 jedn./s)
    operation_cost: Paliwo jądrowe
    tech_requirement: advanced-nuclear-reactor
  - id: nuclear-power-plant
    name: Elektrownia jądrowa
    tier: 5
    type: energia
    cost: [ {itemId: steel-plate, qty: 300}, {itemId: advanced-circuit, qty: 150}, {itemId: heat-exchanger, qty: 100} ]
    function: Integruje reaktory (+200 jedn./s)
    operation_cost: Paliwo jądrowe
    tech_requirement: nuclear-power-plant

  - id: autonomous-module
    name: Moduł autonomiczny
    tier: 5
    type: automatyzacja
    cost: [ {itemId: steel-plate, qty: 50}, {itemId: advanced-circuit, qty: 30}, {itemId: electric-engine, qty: 20} ]
    function: Automatyzuje dowolny proces idle
    operation_cost: 150 kW
    tech_requirement: autonomous-modules

  - id: solar-panel
    name: Panel słoneczny
    tier: 6
    type: energia
    cost: [ {itemId: steel-plate, qty: 15}, {itemId: electronic-circuit, qty: 10}, {itemId: copper-plate, qty: 5} ]
    function: Produkcja energii w dzień (+10 jedn./s)
    operation_cost: Brak
    tech_requirement: solar-cells
  - id: solar-panel-farm
    name: Farma paneli słonecznych
    tier: 6
    type: produkcja
    cost: [ {itemId: steel-plate, qty: 50}, {itemId: electronic-circuit, qty: 30}, {itemId: advanced-circuit, qty: 20} ]
    function: Produkcja paneli słonecznych (+2/s)
    operation_cost: 100 kW
    tech_requirement: solar-panel-farm

  - id: geothermal-probe
    name: Sonda geotermiczna
    tier: 6
    type: energia
    cost: [ {itemId: steel-plate, qty: 30}, {itemId: pipe, qty: 15}, {itemId: electronic-circuit, qty: 10} ]
    function: Zwiększa efektywność wydobycia ciepła o 25%
    operation_cost: 40 kW
    tech_requirement: geothermal-probes

  - id: geothermal-installation
    name: Instalacja geotermalna
    tier: 6
    type: energia
    cost: [ {itemId: steel-plate, qty: 80}, {itemId: pipe, qty: 40}, {itemId: advanced-circuit, qty: 30} ]
    function: Pasywna energia geotermalna (+40 jedn./s)
    operation_cost: Brak
    tech_requirement: geothermal-probes
  - id: ai-core
    name: AI Core
    tier: 6
    type: ai
    cost: [ {itemId: steel-plate, qty: 100}, {itemId: advanced-circuit, qty: 50}, {itemId: processor-unit, qty: 30} ]
    function: +20% do wszystkich bonusów idle
    operation_cost: 200 kW
    tech_requirement: idle-artificial-intelligence

  - id: ai-server
    name: Serwer AI
    tier: 6
    type: ai
    cost: [ {itemId: steel-plate, qty: 200}, {itemId: advanced-circuit, qty: 100}, {itemId: processor-unit, qty: 50} ]
    function: Automatyzuje badania (+25% szybkości)
    operation_cost: 350 kW
    tech_requirement: ai-server

  - id: rocket-silo
    name: Silos rakietowy
    tier: 7
    type: rakiety
    cost: [ {itemId: steel-plate, qty: 500}, {itemId: concrete, qty: 100}, {itemId: electric-engine, qty: 100}, {itemId: advanced-circuit, qty: 100} ]
    function: Wystrzeliwuje rakiety
    operation_cost: 5 MW podczas startu
    tech_requirement: rocket-technology
  - id: orbital-module-factory
    name: Fabryka modułów orbitalnych
    tier: 7
    type: kosmiczne
    cost: [ {itemId: steel-plate, qty: 100}, {itemId: advanced-circuit, qty: 50}, {itemId: electric-engine, qty: 30} ]
    function: Produkuje moduły orbitalne (1/min)
    operation_cost: 400 kW
    tech_requirement: orbital-modules

  - id: satellite-communication-station
    name: Stacja komunikacji satelitarnej
    tier: 7
    type: kosmiczne
    cost: [ {itemId: steel-plate, qty: 200}, {itemId: advanced-circuit, qty: 150}, {itemId: electric-engine, qty: 100}, {itemId: processor-unit, qty: 50} ]
    function: +15% badań pasywnie
    operation_cost: 300 kW
    tech_requirement: satellite-communication-station

  - id: life-support-system
    name: System podtrzymywania życia
    tier: 8
    type: kosmiczne
    cost: [ {itemId: composite-materials, qty: 300}, {itemId: advanced-circuit, qty: 200}, {itemId: processor-unit, qty: 100} ]
    function: +20% do wszystkich efektywności
    operation_cost: 500 kW
    tech_requirement: life-support-system
  - id: automatic-docking
    name: Automatyczne dokowanie
    tier: 8
    type: kosmiczne
    cost: [ {itemId: composite-materials, qty: 400}, {itemId: advanced-circuit, qty: 300}, {itemId: electric-engine, qty: 200}, {itemId: processor-unit, qty: 100} ]
    function: +25% do wszystkich procesów kosmicznych
    operation_cost: 600 kW
    tech_requirement: automatic-docking

  - id: orbital-research-module
    name: Moduł badawczy orbitalny
    tier: 8
    type: kosmiczne
    cost: [ {itemId: composite-materials, qty: 300}, {itemId: advanced-circuit, qty: 250}, {itemId: processor-unit, qty: 150} ]
    function: Generuje purple packs (+5/s)
    operation_cost: 800 kW
    tech_requirement: orbital-research-module

  - id: space-station
    name: Stacja kosmiczna
    tier: 8
    type: kosmiczne
    cost: [ {itemId: composite-materials, qty: 1000}, {itemId: advanced-circuit, qty: 500}, {itemId: processor-unit, qty: 300}, {itemId: superconductor, qty: 200} ]
    function: +100 jedn./s energii, +50 purple packs/s
    operation_cost: 2 MW
    tech_requirement: space-station
